"""add closed_paid and closed_abandoned account states

Revision ID: 2f4bc391a33c
Revises: 5d6cc313aeb7
Create Date: 2026-08-29 18:50:26.996057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f4bc391a33c'
down_revision: Union[str, None] = '5d6cc313aeb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Hand-written rather than autogenerated -- Alembic's autogenerate does
    # not reliably detect Postgres enum value additions. ADD VALUE works
    # inside a transaction on PG12+ (this project runs pg16) as long as the
    # new value isn't used in the same transaction, which it isn't here.
    op.execute("ALTER TYPE account_current_state ADD VALUE IF NOT EXISTS 'closed_paid'")
    op.execute("ALTER TYPE account_current_state ADD VALUE IF NOT EXISTS 'closed_abandoned'")


def downgrade() -> None:
    # Postgres has no ALTER TYPE ... DROP VALUE -- removing an enum value
    # requires rebuilding the type and every column using it. Not
    # implemented; downgrading past this revision is not supported.
    pass
