"""add created_at to decision_logs for reliable ordering

Revision ID: 834e0783e3f1
Revises: dc803d8ff108
Create Date: 2026-09-02 22:28:39.740269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '834e0783e3f1'
down_revision: Union[str, None] = 'dc803d8ff108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decision_logs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decision_logs', 'created_at')
    # ### end Alembic commands ###
