"""add dispute_review account state

Revision ID: a3f9c1d84e27
Revises: b7fa2b3a4acb
Create Date: 2026-08-30 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3f9c1d84e27'
down_revision: Union[str, None] = 'b7fa2b3a4acb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Hand-written, not autogenerated -- same reason as 2f4bc391a33c: Alembic
    # autogenerate doesn't reliably detect Postgres enum value additions.
    # Adding the UPPERCASE member NAME directly this time (not the lowercase
    # .value) -- b7fa2b3a4acb already diagnosed that account_current_state_enum
    # has no values_callable, so SQLAlchemy stores/reads each member's NAME,
    # not its .value. No two-step correction needed here since the gotcha is
    # already known going in.
    op.execute("ALTER TYPE account_current_state ADD VALUE IF NOT EXISTS 'DISPUTE_REVIEW'")


def downgrade() -> None:
    # Postgres has no ALTER TYPE ... DROP VALUE -- not implemented; see
    # 2f4bc391a33c's downgrade for the same limitation.
    pass
