"""add invoice root cause

Revision ID: f53cb24488a8
Revises: f77b57a510b7
Create Date: 2026-08-27 16:16:25.489881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f53cb24488a8'
down_revision: Union[str, None] = 'f77b57a510b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('true_root_cause', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'true_root_cause')
    # ### end Alembic commands ###
