"""initial schema

Revision ID: f77b57a510b7
Revises: 
Create Date: 2026-08-27 15:17:41.973842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f77b57a510b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('segment', sa.String(length=100), nullable=False),
    sa.Column('relationship_start_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('segment', sa.String(length=100), nullable=False),
    sa.Column('relationship_start_date', sa.Date(), nullable=False),
    sa.Column('archetype', sa.String(length=50), nullable=True),
    sa.Column('true_recovery_probability', sa.Float(), nullable=True),
    sa.Column('true_promise_keep_probability', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customers_merchant_id', 'customers', ['merchant_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'DISPUTED', 'PROMISED', 'PAID', 'WRITTEN_OFF', name='invoice_status'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index('ix_invoices_customer_id', 'invoices', ['customer_id'], unique=False)
    op.create_index('ix_invoices_due_date_status', 'invoices', ['due_date', 'status'], unique=False)
    op.create_table('account_state',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('current_state', sa.Enum('OVERDUE', 'ASSESSMENT', 'WAIT', 'REMIND', 'ESCALATE', 'PROMISE', 'MONITORING', 'KEPT', 'BROKEN', 'REASSESS', 'CLOSED', name='account_current_state'), nullable=False),
    sa.Column('recoverability_score', sa.Float(), nullable=False),
    sa.Column('promise_score', sa.Float(), nullable=False),
    sa.Column('expected_payment_date', sa.Date(), nullable=True),
    sa.Column('revenue_at_risk', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('next_action', sa.Enum('WAIT', 'EMAIL', 'WHATSAPP', 'PAYMENT_LINK', 'VOICE', 'ESCALATE', 'STOP', name='action_type'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('invoice_id')
    )
    op.create_index('ix_account_state_current_state', 'account_state', ['current_state'], unique=False)
    op.create_table('attribution_records',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('treatment_group', sa.Enum('ACTED', 'CONTROL', name='treatment_group'), nullable=False),
    sa.Column('baseline_predicted_recovery', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('observed_recovery', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('incremental_recovery', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('invoice_id')
    )
    op.create_table('decision_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=100), nullable=False),
    sa.Column('model_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('policy_checks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_decision_logs_invoice_id', 'decision_logs', ['invoice_id'], unique=False)
    op.create_table('feature_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('feature_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payment_features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('promise_features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('behavior_features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feature_snapshots_lookup', 'feature_snapshots', ['merchant_id', 'customer_id', 'invoice_id', 'feature_timestamp'], unique=False)
    op.create_table('interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=100), nullable=False),
    sa.Column('outcome', sa.String(length=100), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_interactions_customer_id', 'interactions', ['customer_id'], unique=False)
    op.create_index('ix_interactions_invoice_id', 'interactions', ['invoice_id'], unique=False)
    op.create_table('payment_promises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('promised_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('promised_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'KEPT', 'BROKEN', name='promise_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payment_promises_invoice_id', 'payment_promises', ['invoice_id'], unique=False)
    op.create_index('ix_payment_promises_status', 'payment_promises', ['status'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'FAILED', 'REVERSED', name='payment_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payments_invoice_id', 'payments', ['invoice_id'], unique=False)
    op.create_table('recovery_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('action_type', postgresql.ENUM('WAIT', 'EMAIL', 'WHATSAPP', 'PAYMENT_LINK', 'VOICE', 'ESCALATE', 'STOP', name='action_type', create_type=False), nullable=False),
    sa.Column('expected_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('policy_result', sa.Enum('ALLOWED', 'BLOCKED', 'ESCALATED', name='policy_result'), nullable=False),
    sa.Column('result', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recovery_actions_invoice_id', 'recovery_actions', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recovery_actions_invoice_id', table_name='recovery_actions')
    op.drop_table('recovery_actions')
    op.drop_index('ix_payments_invoice_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_payment_promises_status', table_name='payment_promises')
    op.drop_index('ix_payment_promises_invoice_id', table_name='payment_promises')
    op.drop_table('payment_promises')
    op.drop_index('ix_interactions_invoice_id', table_name='interactions')
    op.drop_index('ix_interactions_customer_id', table_name='interactions')
    op.drop_table('interactions')
    op.drop_index('ix_feature_snapshots_lookup', table_name='feature_snapshots')
    op.drop_table('feature_snapshots')
    op.drop_index('ix_decision_logs_invoice_id', table_name='decision_logs')
    op.drop_table('decision_logs')
    op.drop_table('attribution_records')
    op.drop_index('ix_account_state_current_state', table_name='account_state')
    op.drop_table('account_state')
    op.drop_index('ix_invoices_due_date_status', table_name='invoices')
    op.drop_index('ix_invoices_customer_id', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('ix_customers_merchant_id', table_name='customers')
    op.drop_table('customers')
    op.drop_table('merchants')
    # ### end Alembic commands ###
